//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkUp
    {
        public int MarkUpId { get; set; }
        public Nullable<int> InstitutionId { get; set; }
        public Nullable<decimal> MarkUp1 { get; set; }
    }
}
