//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Api
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StationaryManagementSystemEntities : DbContext
    {
        public StationaryManagementSystemEntities()
            : base("name=StationaryManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Institution> Institutions { get; set; }
        public virtual DbSet<Inventary> Inventaries { get; set; }
        public virtual DbSet<MarkUp> MarkUps { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<InstitutionType> InstitutionTypes { get; set; }
        public virtual DbSet<InventaryType> InventaryTypes { get; set; }
    }
}
